language: python

python:
  - "3.5"

services:
  - docker

cache: pip

install:
  - pip3 install /swarmrob -r swarmrob/requirements.txt
  - pip3 install /swarmrob/tests/dummy_daemon -r /swarmrob/tests/dummy_daemon/requirements.txt

script:
  - ./swarmrob/unittest.sh
