language: python

python:
  - "3.5"

services:
  - docker

cache: pip

install:
  - pip3 install $PWD/swarmrob -r $PWD/swarmrob/requirements.txt
  - pip3 install $PWD/swarmrob/tests/dummy_daemon -r $PWD/swarmrob/tests/dummy_daemon/requirements.txt

script:
  - ./swarmrob/unittest.sh
