language: python

python:
  - "3.5"

before_install:
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - sudo apt-get update
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce docker-ce-cli containerd.io

cache: pip

install:
  - pip3 install $PWD/swarmrob -r $PWD/swarmrob/requirements.txt
  - pip3 install $PWD/swarmrob/tests/dummy_daemon -r $PWD/swarmrob/tests/dummy_daemon/requirements.txt

before_script:
  - swarmrob_dummy

script:
  - ./swarmrob/unittest.sh
