language: python

python:
  - "3.5"

before_install:
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - sudo apt-get update
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce docker-ce-cli containerd.io
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - "./miniconda.sh -b"
  - export PATH=/home/travis/miniconda2/bin:$PATH
  - conda update --yes conda
  #- sudo rm -rf /dev/shm
  #- sudo ln -s /run/shm /dev/shm

cache: pip

install:
  - pip3 install $PWD/swarmrob -r $PWD/swarmrob/requirements.txt
  - pip3 install $PWD/swarmrob/tests/dummy_daemon -r $PWD/swarmrob/tests/dummy_daemon/requirements.txt
  - conda install --yes python="2.7" sphinx
  - pip install --user travis-sphinx 

before_script:
  - swarmrob_dummy

script:
  - ./swarmrob/unittest.sh
  - /usr/local/bin/sphinx-apidoc -f -o $PWD/swarmrob/docs/source $PWD/swarmrob
  - travis-sphinx build --source=$PWD/swarmrob/docs/source
after_success:
  - travis-sphinx deploy

